
services:
  frontend:
    build:
      context: frontend
      target: development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    networks:
      - server
    depends_on:
      - backend
  backend:
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    networks:
      - database
      - server
    expose:
      - 80000
  database:
    image: mongo
    restart: always
    volumes:
      - ./data:/data
    networks:
      - database
    expose:
      - 27017
    ports:
      - 27017:27017
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=admin
    #   - MONGODB_INITDB_ROOT_PASSWORD=12345
    #   - MONGODB_INITDB_DATABASE=imakebot

networks:
  database:
  server: